### ISSUE TITLE
[BUG] Filedialog false background color 

### ISSUE THREAD

**Issue by ckvsoft** [thonny/thonny#2072] opened 2021-12-09 15:51 UTC
When using the dark themes the Open Filedialogs background color has same color as the textcolor.
![Screenshot_20211209_164755](https://user-images.githubusercontent.com/16374447/145429283-d7fdb758-db2a-4882-a354-a9f5c2846c0f.png)

lg Chris

**Comment by aivarannamaa** [comment] 2021-12-09 20:48
Thank you for the report! Which Linux distro and which desktop environment are you using?

**Comment by ckvsoft** [comment] 2021-12-10 07:26
Oh sorry.
Kubuntu 21.10 KDE

**Comment by aivarannamaa** [comment] 2021-12-25 15:37
I now installed Kubuntu 21.10 to a VM but I can't reproduce it.

You're using dark system theme and Clean Dark Thonny theme, right?

**Comment by ckvsoft** [comment] 2021-12-26 10:33
Breeze dark, and in Thonny I also tried raspberry dark. It doesn't matter what settings I try. In the dark mode, the file open dialog always has a white background and white text. Got this on my laptop and also on a desktop with Kubuntu 20.04

But I know that. I program a cash register in c ++. The users often have errors that I can hardly understand here. But don't worry about it. It works that way too ;-)

**Comment by aivarannamaa** [comment] 2022-01-11 08:29
Didn't just re-starting Thonny achieve the same effect?

**Comment by ckvsoft** [comment] 2022-01-11 10:38
Of course not. Do you think I haven't done that since the Thonny installation?

**Comment by aivarannamaa** [comment] 2024-06-15 07:27
Will be fixed under #2756

**Closed by aivarannamaa** 2024-06-15 07:27 UTC
Labels: linux, tk
