### ISSUE TITLE
Request for 64-bit Python

### ISSUE THREAD

**Issue by jr751** [thonny/thonny#862] opened 2019-08-16 15:41 UTC
I want to be able to use modules like tensorflow and TFLearn with Thonny, but it doesn't work. I think the reason why is because they need the 64-bit version of Python. But Thonny only comes with the 32-bit version of Python. I would like to request that you modify Thonny so that it comes with 64-bit Python instead. That way we can use some of these commonly used machine learning modules. I think this is the number one reason why Thonny isn't more popular. I just can't use it for the things I need. Overwise, I really like Thonny's minimalist style a lot and would use it a bunch.

**Comment by aivarannamaa** [comment] 2019-08-18 06:13
I can't just replace 64-bit with 32-bit, because Thonny is also being used on 32-bit computers. I'll consider adding 64-bit variant later.

I recommend you install separate 64-bit Python and let Thonny use it (Tools => Options => Interpreter)

**Comment by jr751** [comment] 2019-11-14 19:11
No, this really doesn't solve the problem either. For example, you can do as you suggested, but then for example, if I want to use Matplotlib I run into problems. You can install Matplotlib and its dependencies, however, when you then try to run it by typing 'import matplotlib.pyplot as plt' you get the error message "OSError: [WinError 193] %1 is not a valid Win32 application". So why isn't this working?

**Comment by aivarannamaa** [comment] 2019-11-14 20:50
I can't reproduce this. 

I used Thonny 3.2.3 Windows bundle (ie. with 32-bit Python 3.7.5). I installed separately 64-bit Python 3.8 from python.org and assigned it as Thonny's back-end (Tools => Options => Interpreter => Alternative Python 3 interpreter). Then I installed matplotlib from Tools => Manage packages (Had to select 3.2.0rc1 from "..." button, because latest stable doesn't provide binaries for Python 3.8).

After this I could run the example code: 

```
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```

**Comment by jr751** [comment] 2019-11-15 15:49
No, still not working for me and giving me the same error. The only thing I am doing different from you is using Python 3.7.5 (64-bit). I can't use Python 3.8 because it won't let you install the grpcio module, and I need that dependency if I am to user tensorflow. I switched the matplotlib version to 3.2.0rc1. Same error message though. As for its dependencies, I am using numpy 1.17.0, setuptools 41.1.0, cycler 0.10.0, python-dateutil 2.8.1, kiwisolver 1.0.1.

**Comment by aivarannamaa** [comment] 2019-11-16 05:51
> when you then try to run it by typing 'import matplotlib.pyplot as plt' into the python shell you get the error message "OSError: [WinError 193] %1 is not a valid Win32 application"

I would expect this when you somehow get 64-bit matplotlib into 32-bit python. Please check whether you notice something suspicious in the output of following script:

```
import sys
import platform

print("ARCH:", platform.architecture())
print("EXE:", sys.executable)
print("PATH:", sys.path)
```

**Comment by pssolanki111** [comment] 2020-11-21 16:50
@aivarannamaa Hey Aivar, sorry for troubling you again. I was wondering which version (or rather edition) of thonny should I use for 64 bit Windows 10. I just tried installing [THIS](https://github.com/thonny/thonny/releases/download/v3.3.0/thonny-3.3.0.exe) one but it doesn't get installed.

**Comment by aivarannamaa** [comment] 2020-11-21 18:12
@pssolanki111, this should work both in 32 and 64-bit Win 7 and Win 10.

What do you mean by not getting installed? Did you get an error message?

**Comment by pssolanki111** [comment] 2020-11-21 18:15
@aivarannamaa  Yes, I did get an error saying

> This app can't be installed in your computer. Contact the app vendor to get a compatible version.

(It wasn't the exact same message as above but it meant somewhat the same)

**Comment by aivarannamaa** [comment] 2020-11-21 19:00
Do you have "regular" PC, ie. with Intel or AMD processor? Not ARM?
In this case I recommend to download it again -- maybe the download was broken first time.

**Comment by pssolanki111** [comment] 2020-11-22 05:43
@aivarannamaa Yes. It's AMD Ryzen 3. I'll try re-downloading.

**Comment by pssolanki111** [comment] 2020-11-22 07:33
It did work this time, Thanks :)

**Comment by aivarannamaa** [comment] 2021-12-26 09:19
The main Windows installer will come with 64-bit Python 3.10 starting with Thonny 4.0

**Closed by aivarannamaa** 2021-12-26 09:19 UTC

**Comment by pssolanki111** [comment] 2021-12-26 12:04
@aivarannamaa great. thonny helped me a lot when i started out and i recommend it to anyone I can :) 

just wanted to say thanks for the wonderful tool.
