### ISSUE TITLE
Thonny Eror message

### ISSUE THREAD

**Issue by miker-rpi** [thonny/thonny#1551] opened 2021-01-18 11:01 UTC
This is occasionally displayed when pressing enter for a newline.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/thonny/plugins/outline.py", line 126, in _on_select
    lineno = self.tree.item(self.tree.focus())["values"][0]
IndexError: string index out of range
```

lenovo T410 Linux Mint 20.1
Have reinstalled Thonny but this is not a cure.
Otherwise everything else seems to run ok - its a just  bit annoying.

Mike

**Comment by aivarannamaa** [comment] 2021-01-18 11:23
Thank you for the report! It seems to be duplicate of #1543 and the fix will be in Thonny 3.3.3.

In the meanwhile the work-around is to close "Outline" view (and maybe also restart Thonny).

**Closed by aivarannamaa** 2021-01-18 11:23 UTC
