### ISSUE TITLE
pysine package with latest MS VIsual C++ 2019 displays Error 1 

### ISSUE THREAD

**Issue by victorgithubvv** [thonny/thonny#790] opened 2019-06-28 23:11 UTC
Greetings;
On a Windows 10 computer, I attempted to install pysine and pyaudio and its dependencies, rebooted the computer (and thus Thonny). As shown in the attachment , I receive an error 1.  Also when I attempt to install pysine or pyaudio it does not show up in the manage package plugins list. The code below should on a windows 10 beep the built in speaker. I have not tried it yet on Raspberry Pi 3B+ pitop with pitop speaker and Debian Buster OS. 

``from pysine import sine
from time import sleep

while True:
    sine(frequency=640.0, duration=1.0)
    sleep(1)
    sine(frequency=440.0, duration=1.0)
    sleep(1)

      # plays a 1s sine wave at 440 Hz
![Annotation 2019-06-28 175844](https://user-images.githubusercontent.com/17308686/60375556-65fefb00-99cf-11e9-8c46-398ec587583f.png)

**Comment by aivarannamaa** [comment] 2019-06-29 05:38
Currently Thonny comes without the files required for building native Python packages.

Duplicate of #361

**Closed by aivarannamaa** 2019-06-29 05:38 UTC
