### ISSUE TITLE
Internal error when attempting to clear shell

### ISSUE THREAD

**Issue by willbprog127** [thonny/thonny#964] opened 2019-10-27 02:16 UTC
Greetings!

After using Thonny 3.2.1 for a few hours, I tried to clear the Shell display by right-clicking in the Shell then choosing 'Clear'.  The following internal error popped up:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.7/dist-packages/thonny/shell.py", line 1235, in _clear_shell
    self._clear_content(end_index)
  File "/usr/local/lib/python3.7/dist-packages/thonny/shell.py", line 1308, in _clear_content
    btn_pos = float(self.index(btn))
ValueError: could not convert string to float: 
```
This is running the Thonny from `pip` installation.
* Debian 10 amd64
* Python 3.7.3

Thank you! :smiley:

**Comment by aivarannamaa** [comment] 2019-10-27 10:48
Thank you for the report!

I'm not able to reproduce this. Can you do it again or was it a single case?

**Comment by willbprog127** [comment] 2019-10-27 20:51
> Can you do it again or was it a single case?

After 'something happened' (I don't know what specifically) it would do the error above continuously.  I could not clear the shell after that point unless I closed Thonny and tried again.

**Comment by aivarannamaa** [comment] 2020-03-16 17:32
Duplicate of #1091

**Closed by aivarannamaa** 2020-03-16 17:32 UTC
