### ISSUE TITLE
Thonny locks up while editing

### ISSUE THREAD

**Issue by AshDini** [thonny/thonny#2247] opened 2022-04-13 21:56 UTC
Thonny locks up while editing (using Thonny 4.0.0b2)
![Image88](https://user-images.githubusercontent.com/66854499/163276549-c500cb0b-d7e1-42fa-a960-403209a8ab48.jpg)

A little blue circle is circling, but it does not show on the screenshot.

**Comment by aivarannamaa** [comment] 2022-04-18 20:53
Thank you for the report!

After you force-close Thonny, can you repeat this situation? Can you give me example code and steps for reproducing this?

**Comment by AshDini** [comment] 2022-04-20 20:12
Hi Aivar,

It happened many times, but I could not find a common reason for it to
happen. Sorry I can not be more help.

Unfortunately, I had to switch back to the current (3.3.13) version

Regards,

Bob Stanton

**Comment by chicory-ru** [comment] 2022-04-21 03:17
You can repeat it by opening a large enough code and dragging the scroll up and down many times.

**Comment by aivarannamaa** [comment] 2022-05-21 08:44
I hope this issue was fixed in #2258, available since 4.0.0b3. Please reopen if you still get this error!

**Comment by AshDini** [comment] 2022-10-11 08:31
It just happened during editing the source code...

**Comment by aivarannamaa** [comment] 2022-10-12 05:59
@AshDini, with which version did it happen this time?

**Comment by AshDini** [comment] 2022-10-15 20:03
That was version 13. 14 seem to be ok.

**Comment by aivarannamaa** [comment] 2022-12-28 16:35
Assuming the issue is fixed in 4.0.1

**Closed by aivarannamaa** 2022-12-28 16:35 UTC
Labels: editor

**Comment by AshDini** [comment] 2022-12-28 21:01
Yes, this issue have been fixed.
