### ISSUE TITLE
Bug: Caps Lock being on, prevents keyboard command "Ctrl-s" from saving a file 

### ISSUE THREAD

**Issue by md-hexdrive** [thonny/thonny#1240] opened 2020-06-13 15:57 UTC
When I am trying to save a file in Thonny and my Caps Lock key is on, the keyboard command "Ctrl-s" won't save the file.

I will try to submit a pull request to fix this later.

P.S. I LOVE Thonny! Thank You for creating it.

**Comment by aivarannamaa** [comment] 2020-06-16 11:33
This is a known issue (duplicate of #331). Unfortunately, at the moment I don't have a good idea how to solve this.

I'll look into this later.

**Closed by aivarannamaa** 2020-06-16 11:33 UTC
