### ISSUE TITLE
Plotting sub-window hangs when displaying plot with matplotlib.pyplot

### ISSUE THREAD

**Issue by gvwilson** [thonny/thonny#707] opened 2019-03-17 14:28 UTC
Run the following code interactively in the Shell pane:

```
import seaborn as sns
import matplotlib.pyplot as plt
axes = sns.scatterplot(x=[1, 2, 3], y=[5, 1, 3])
plt.show()
```

1.  Plot window appears (yay).
2.  Click on "window close" (little red button in upper left on MacOS).
3.  Plot window does not close. Instead, after a delay of several seconds, the spinning rainbow disk that indicates a hung application appears.
4.  Despite this, I am able to type more commands into the interactive shell (but not able to bring up a second plot).

Using:
-   Thonny 3.1.2
-   Python 3.7.2
-   MacOS 10.13.6
-   Seaborn 0.9.0
-   Matplotlib 3.0.3

**Comment by aivarannamaa** [comment] 2019-03-17 17:29
Duplicate of #676

**Closed by aivarannamaa** 2019-03-17 17:29 UTC
