### ISSUE TITLE
thonny crashes on shell > clear

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#1118] opened 2020-03-16 17:24 UTC
thonny crashes on shell > clear

happend several times today.
no idea how to reproduce (sorry, but maybe the traceback helps...)

Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/shell.py", line 1268, in _clear_shell
    self._clear_content(end_index)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/shell.py", line 1361, in _clear_content
    btn_pos = float(self.index(btn))
ValueError: could not convert string to float: 

thonny version 3.2.7
on linux (64bit), python 3.6.9 (64bit), tk 8.6.8

**Comment by aivarannamaa** [comment] 2020-03-16 17:32
Thank you for the report!
This seems to be duplicate of #1091

**Comment by kr-g** [comment] 2020-03-16 17:38
last time it happened during argparse. 
no "squeezed" content here.

**Comment by aivarannamaa** [comment] 2020-03-16 17:59
Alright, I leave it open then.

**Comment by kr-g** [comment] 2020-03-30 13:03
it did not occur again ...

**Comment by aivarannamaa** [comment] 2020-10-28 18:44
Duplicate of #1091

**Closed by aivarannamaa** 2020-10-28 18:44 UTC
