### ISSUE TITLE
Not working with Adafruit CircuitPython 7.0.0-rc.1 on RP2040

### ISSUE THREAD

**Issue by LovelyA72** [thonny/thonny#1958] opened 2021-09-03 15:05 UTC
When I connect RP2040 board with CircuitPython 7.0.0-RC.1loaded with Thonny, I only got an empty console and an empty file explorer. ctrl+c does nothing in the console. The board will have its white LED on to confirm that it's connected to the console but I can't send out any commands from the console.

The console also occasionally prints
```
WARNING:root:Unexpected echo. Expected b'help\r\n', got b''
```

However, This might be an issue with Adafruit's CircuitPython firmware

**Comment by aivarannamaa** [comment] 2021-09-03 15:23
Thank you for the report! I'll try to find time for reproducing this in the weekend

**Comment by aivarannamaa** [comment] 2021-09-06 21:19
I think I found the reason -- CP7 has removed a marker string which is used by Thonny as confirmation about entering raw REPL (https://github.com/adafruit/circuitpython/issues/5307). Hopefully they put it back before final release.

**Comment by carlskii** [comment] 2021-09-07 22:43
+1 exactly the same problem for me.

**Comment by aivarannamaa** [comment] 2021-11-06 07:44
closing, as the final CP 7.0 fixed it

**Closed by aivarannamaa** 2021-11-06 07:44 UTC
Labels: MicroPython
