### ISSUE TITLE
v3.1.1 doesn't work with Windows

### ISSUE THREAD

**Issue by nathanRamaNoodles** [thonny/thonny#684] opened 2019-02-11 03:35 UTC
I am getting an error when I load Thonny:
![thonny not starting error](https://user-images.githubusercontent.com/32442782/52545256-ad1b8500-2d7b-11e9-989d-5bfa6cdc1b78.PNG)
'Nonetype' object has no attribute 'call'

**Comment by aivarannamaa** [comment] 2019-02-11 05:46
Similar issue was discussed here: #639
Do same suggestions work for you?

**Comment by Gefionious** [comment] 2019-03-20 12:09
I had the same issue and the fix was the same (#639). I think the CSR is installed as part of a pretty popular bluetooth adapter driver or something, I have not completely traced the source but that was frustrating. There was no mention on the FAQ or the Wiki. Also I downloaded Thonny 3.1.2 so problem still there.

Thank you. My son loves using your tool and suggested I start using it, but it was very frustrating not being able to launch. I ended up uninstalling all my other Python versions, libraries and IDE's thinking it was some sort of conflict somewhere, obviously in the right general direction but all wasted effort. Sigh.

**Comment by aivarannamaa** [comment] 2019-03-20 12:21
Thank you for the feedback! I'll make sure the fix will be in version 3.2

**Comment by aivarannamaa** [comment] 2019-06-07 09:43
Duplicate of #639

**Closed by aivarannamaa** 2019-06-07 09:43 UTC

**Comment by Gefionious** [comment] 2019-06-07 13:05
Thank you!
