### ISSUE TITLE
PROBLEM IN THONNY'S BACK-END: Exception while handling 'Run' (ConnectionError: EOF).

### ISSUE THREAD

**Issue by rusty-error** [thonny/thonny#2485] opened 2022-10-01 01:15 UTC
I am trying to run an example code to test wifi but I am getting an error like this. Here is the screenshot of the whole window. What is the problem? Thank you for your time.
![Screenshot (65)](https://user-images.githubusercontent.com/114786953/193377446-85f3d677-5cae-4cf4-913b-376e79d3bc6b.png)

**Comment by aivarannamaa** [comment] 2022-10-01 04:54
It looks like the device or MicroPython interpreter had a reset. What's in your boot.py ?

**Comment by rstmsvk** [comment] 2022-10-01 07:56
It's empty. I just uploaded the firmware. I have tried some other interpreters and got a similar error. Also, I check the board with Arduino ide in order to see if it was broken or not and the board was fine. It is working fine when I use Arduino ide.

**Comment by aivarannamaa** [comment] 2022-10-02 07:45
Which exact device are you using? Does it make a difference if you uncheck "Restart interpreter before running a script" at interpteter configuration page (click on the intepreter switcher at the lower-right corner of Thonny's main window and select "Configure interpreter").

**Comment by rstmsvk** [comment] 2022-10-02 11:34
I am using ESP32-WROOM-32D DevkitC-V4. I unchecked it, and I am still getting the same error, unfortunately.

**Comment by springjools** [comment] 2022-10-04 19:26
I get this too with a raspberry pi pico WH

**Comment by rstmsvk** [comment] 2022-10-13 15:19
I got an esp8266 now and it is running fine. I think the one that I have is broken.

**Comment by aivarannamaa** [comment] 2023-01-14 18:11
Closing as I'm not able to reproduce. Please reopen if you have more clues to add.

**Closed by aivarannamaa** 2023-01-14 18:11 UTC
Labels: MicroPython

**Comment by Mariopolonia0** [comment] 2024-09-07 23:28
i have the problem
