### ISSUE TITLE
Shell relocation

### ISSUE THREAD

**Issue by SpacedOutKid** [thonny/thonny#932] opened 2019-10-06 00:32 UTC
Hey everyone, have been trying to get this for awhile but is their anyway to change the shell view so I can see it on the side and not at the bottom?

**Comment by SpacedOutKid** [comment] 2020-01-29 21:49
I Guess  im super late too haha but I ended up getting it a couple weeks after i asked  thanks for the reply though

**Comment by aivarannamaa** [comment] 2020-10-14 07:49
Duplicate of #544

**Closed** 2020-10-24 08:37 UTC
