### ISSUE TITLE
Cannot Flash or Erase Micropython on ESP8266

### ISSUE THREAD

**Issue by jomasnash** [thonny/thonny#930] opened 2019-10-04 13:24 UTC
The Tools/Erase Tools/Flash menu item is blanked since 3.2.1 (Worked before)

Windows 7.
Thonny 3.2.1.
Plugins thonny-esp and esptool are installed.

**Comment by aivarannamaa** [comment] 2019-10-04 20:08
Duplicate of #924

**Closed by aivarannamaa** 2019-10-04 20:08 UTC
