### ISSUE TITLE
Thonny Prevents pygame Window Close

### ISSUE THREAD

**Issue by troywein** [thonny/thonny#2929] opened 2023-09-11 18:08 UTC
Hello,

When using pygame in combination with the Thonny IDE on Mac OS, calling pygame.quit() doesn't close the open window.  If running outside Thonny the window closes as expected.  The attached file is a short example that can be used to reproduce this issue on the Mac.
____________
[window_hang.py.zip](https://github.com/thonny/thonny/files/12579174/window_hang.py.zip)

**Comment by aivarannamaa** [comment] 2023-09-11 18:18
This is expected. Thonny doesn't close the process after the script ends in order to allow inspecting the resulting variables. 

You can force closing the process by adding `exit()` after the `pygame.quit()`.

**Comment by troywein** [comment] 2023-09-11 18:24
Hello Aivar,

Thanks for the quick response.  The exit() isn’t an option for our course as we would like the cadets to do some additional work after the window closes.  Additionally, it closes as expected in Thonny on Windows so is causing some confusion in our course between the Windows and Mac users.  Thanks Troy

Dr. Troy Weingart
Professor of Computer & Cyber Sciences
Office: Fairchild Hall, Suite 6G-115
DSN: 333-7658 COMM: 719-333-7658

On Sep 11, 2023, at 12:18 PM, Aivar Annamaa ***@***.***> wrote:


Caution!
**Don’t click on links or attachments unless you trust the sender. This email came from an external source.**


This is expected. Thonny doesn't close the process after the script ends in order to allow inspecting the resulting variables.

You can force closing the process by adding exit() after the pygame.quit().

**Comment by aivarannamaa** [comment] 2023-09-23 12:54
Sorry for the late reply!

> The exit() isn’t an option for our course as we would like the cadets to do some additional work after the window closes.

Have you been able to achieve the desired behaviour on macOS in another IDE or command line?

According to my test, on macOS the Pygame windows remains hanging even outside of Thonny, e.g. by doing `python3 -i window_freeze.py` (please note the `-i` switch, which forbids the process to close after the script ends).

Perhaps this issue should be discussed in Pygame's issue tracker?

**Comment by troywein** [comment] 2023-09-23 19:25
Hello,

Yes, Pygame works with Visual Studio Code and the window closes as expected.  This script also works as expected via the command line (it doesn’t hang and closes appropriately).  The script will run to completion in Thonny on MacOS with no errors reported, however you must click the stop sign in the menu bar to close the window.  This behavior has been duplicated by many students and and instructors.

There is something about Thonny on MacOS vs Windows vs command line that is preventing the Pygame window from closing.  Thank you for investigating this.


On Sep 23, 2023, at 6:54 AM, Aivar Annamaa ***@***.***> wrote:


Caution!
**Don’t click on links or attachments unless you trust the sender. This email came from an external source.**


Sorry for the late reply!

The exit() isn’t an option for our course as we would like the cadets to do some additional work after the window closes.

Have you been able to achieve the desired behaviour on macOS in another IDE or command line?

According to my test, on macOS the Pygame windows remains hanging even outside of Thonny, e.g. by doing python3 -i window_freeze.py (please note the -i switch, which forbids the process to close after the script ends).

Perhaps this issue should be discussed in Pygame's issue tracker?

**Comment by aivarannamaa** [comment] 2023-09-27 07:20
Just to be clear -- have you been able to close Pygame window without problems AND continue using the same process via Python REPL in macOS?

**Comment by aivarannamaa** [comment] 2023-09-27 18:58
> When using Python REPL (interactive) the window does not close as it does when running the same code as a script on MacOS.

That's the reason Pygame window doesn't close in Thonny and it's Pygame's issue. 

Thonny's work-around is to use "Run => Run current script in terminal".

**Closed by aivarannamaa** 2023-09-27 18:58 UTC
Labels: macOS

**Comment by troywein** [comment] 2023-09-27 19:06
Thanks for your work on this, however, I don’t understand why it works via the terminal and also why it works just fine in Thonny on Windows (btw, also works fine in VSC on Mac and PyCharm on Mac).  Do you have any advice to give to the pygame team?  I’m guessing they will point to Thonny as the issue being that it works just fine in other IDE’s and also via the terminal.

On Sep 27, 2023, at 12:58 PM, Aivar Annamaa ***@***.***> wrote:


Caution!
**Don’t click on links or attachments unless you trust the sender. This email came from an external source.**


When using Python REPL (interactive) the window does not close as it does when running the same code as a script on MacOS.

That's the reason Pygame window doesn't close in Thonny and it's Pygame's issue.

Thonny's work-around is to use "Run => Run current script in terminal".

**Comment by aivarannamaa** [comment] 2023-09-27 20:27
I thought you just confirmed yourself that Pygame doesn't close normally even outside of Thonny on macOS:

> When using Python REPL (interactive) the window does not close as it does when running the same code as a script on MacOS.

**Comment by troywein** [comment] 2023-09-27 20:33
Only when running in REPL.  It closes fine when running as a script.

On Sep 27, 2023, at 2:27 PM, Aivar Annamaa ***@***.***> wrote:


Caution!
**Don’t click on links or attachments unless you trust the sender. This email came from an external source.**


I thought you just confirmed yourself that Pygame doesn't close normally even outside of Thonny on macOS:

When using Python REPL (interactive) the window does not close as it does when running the same code as a script on MacOS.

**Comment by aivarannamaa** [comment] 2023-09-27 21:35
> Only when running in REPL.  It closes fine when running as a script.

Well, that's what I mean -- Thonny always runs the scripts in REPL.
