### ISSUE TITLE
Change Auto Completion

### ISSUE THREAD

**Issue by Remuar** [thonny/thonny#733] opened 2019-04-12 07:46 UTC
Hi,
I discovered Thonny 
and i am very happy... 
thanks for this good tool.
I would like to change the code issued by auto complete :
I would like to change p.ex print to print(' ') or print() because lot of time you will enter something after print.  I also would like to add some personal auto complete like f => France... 
How can I do that?

**Comment by aivarannamaa** [comment] 2019-04-17 13:21
Thank you for the idea!

You can't do this in Thonny at the moment. Also, I don't feel it would be too important feature so I'm postponing this for now.

**Comment by aivarannamaa** [comment] 2020-03-26 06:21
Duplicate of #625

**Closed by aivarannamaa** 2020-03-26 06:21 UTC
