### ISSUE TITLE
Thonny crashing on Mac OS beta Sequoia 

### ISSUE THREAD

**Issue by nissaba** [thonny/thonny#3297] opened 2024-08-30 16:06 UTC
Thonny crashed on MacOs bêta 15.0 (24A5331b)
this is the log I get. 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: C6E18387-BD89-44EC-94CF-1F09029EB1D6
CrashReporter Key:   3FB023CA-2120-9F27-5833-A402996A6707
Hardware Model:      Mac14,9
Process:             Python [14614]
Path:                /Users/USER/*/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python
Identifier:          org.python.python
Version:             3.10.11 (3.10.11)
Code Type:           ARM-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           org.thonny.Thonny [16804]

Date/Time:           2024-08-30 12:02:01.5477 -0400
Launch Time:         2024-08-30 12:02:01.5355 -0400
OS Version:          macOS 15.0 (24A5331b)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 4 Launch Constraint Violation

Triggered by Thread:  0

Thread 0 Crashed:
0   dyld_path_missing             	       0x1025f0b30 _dyld_start + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000016dc1fa38   pc: 0x00000001025f0b30 cpsr: 0x00001000
   far: 0x0000000000000000  esr: 0x00000000  Address size fault

Binary Images:
       0x1025ec000 -        0x10266ffff dyld_path_missing (*) <b5d897df-d536-3668-bbad-a17119439ef0> /dyld_path_missing
       0x1021e0000 -        0x1021e3fff main_executable_path_missing (*) <ef677878-e7fb-329d-bb8b-0f651210d52b> /main_executable_path_missing
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Python","timestamp":"2024-08-30 12:02:01.00 -0400","app_version":"3.10.11","slice_uuid":"ef677878-e7fb-329d-bb8b-0f651210d52b","build_version":"3.10.11","platform":0,"bundleID":"org.python.python","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.0 (24A5331b)","roots_installed":0,"name":"Python","incident_id":"C6E18387-BD89-44EC-94CF-1F09029EB1D6"}
{
  "uptime" : 57000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,9",
  "coalitionID" : 16804,
  "osVersion" : {
    "train" : "macOS 15.0",
    "build" : "24A5331b",
    "releaseType" : "User"
  },
  "captureTime" : "2024-08-30 12:02:01.5477 -0400",
  "codeSigningMonitor" : 1,
  "incident" : "C6E18387-BD89-44EC-94CF-1F09029EB1D6",
  "pid" : 14614,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-08-30 12:02:01.5355 -0400",
  "procStartAbsTime" : 1375362702722,
  "procExitAbsTime" : 1375362976882,
  "procName" : "Python",
  "procPath" : "\/Users\/USER\/*\/Thonny.app\/Contents\/Frameworks\/Python.framework\/Versions\/3.10\/Resources\/Python.app\/Contents\/MacOS\/Python",
  "bundleInfo" : {"CFBundleShortVersionString":"3.10.11","CFBundleVersion":"3.10.11","CFBundleIdentifier":"org.python.python"},
  "storeInfo" : {"deviceIdentifierForVendor":"85EF707A-C05B-5446-B153-556D5814AF14","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.thonny.Thonny",
  "crashReporterKey" : "3FB023CA-2120-9F27-5833-A402996A6707",
  "codeSigningID" : "org.python.python",
  "codeSigningTeamID" : "2SA9D4CVU8",
  "codeSigningFlags" : 587268609,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"4AMA+cEDALAh2DOR4AMUqgdyAZQoAIBSaAIAOfH\/\/xcAAAAAAAAAAA==","atPC":"4AMAkR\/sfJIdAIDSHgCA0gcDABQfAACRYAAf1n8jA9X0T76p\/XsBqQ=="},
  "bootSessionUUID" : "97895CDA-8D8F-42D8-BC72-9FA0BA07BDE5",
  "wakeTime" : 2209,
  "sleepWakeUUID" : "5443D79D-A40A-49D3-B26D-FDAD31ADB274",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":66,"code":4,"namespace":"CODESIGNING","indicator":"Launch Constraint Violation"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1795235,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6136396344},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":4334750512,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":19248,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4334731264,
    "size" : 540672,
    "uuid" : "b5d897df-d536-3668-bbad-a17119439ef0",
    "path" : "\/dyld_path_missing",
    "name" : "dyld_path_missing"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4330487808,
    "size" : 16384,
    "uuid" : "ef677878-e7fb-329d-bb8b-0f651210d52b",
    "path" : "\/main_executable_path_missing",
    "name" : "main_executable_path_missing"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=880K resident=0K(0%) swapped_out_or_unallocated=880K(100%)\nWritable regions: Total=16.1M written=64K(0%) resident=64K(0%) swapped_out=0K(0%) unallocated=16.0M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                         16K        1 \nStack                             16.0M        1 \nVM_ALLOCATE                         16K        1 \n__DATA                              32K        2 \n__DATA_CONST                        48K        2 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         336K        2 \n__TEXT                             544K        2 \n__TPRO_CONST                       288K        1 \nmapped file                        4.3G       18 \npage table in kernel                64K        1 \n===========                     =======  ======= \nTOTAL                              4.3G       32 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "c8807df69b4fbeee79c11aa66ec62abe9a1d8bdc",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "64b1b9b57b7a217c6795f565",
      "factorPackIds" : {
        "SIRI_VALUE_INFERENCE_ENTITY_MATCHER" : "64b1b9e69aa41116c95f6d9c"
      },
      "deploymentId" : 250000003
    },
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "e229c865-41a4-4095-b7d9-4f0e6497d97d",
      "experimentId" : "66b5da86402d6a71d2efe462",
      "deploymentId" : 500000009
    },
    {
      "treatmentId" : "742f90b5-d15c-454e-a26f-bac001d99af9",
      "experimentId" : "66a1616d88ad313392978e6a",
      "deploymentId" : 500000004
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: Mac14,9, BootROM 11881.1.1, proc 10:6:4 processors, 32 GB, SMC 
Graphics: Apple M2 Pro, Apple M2 Pro, Built-In
Display: VG2748, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Display: VG2739, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Jul 26 2024 20:29:22 version 23.10.888.0.41.51.162 FWID 01-1d20bb57
IO80211_driverkit-1302.71 "IO80211_driverkit-1302.71" Aug  7 2024 03:14:49
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: Keychron V6
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB JTAG/serial debug unit
USB Device: USB 10/100 LAN
USB Device: USB 2.0 BILLBOARD
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by pajp** [comment] 2024-08-31 08:47
Looks like another duplicate of https://github.com/thonny/thonny/issues/3283

**Comment by aivarannamaa** [comment] 2024-09-07 14:51
That's right, closing as duplicate

**Closed by aivarannamaa** 2024-09-07 14:51 UTC

**Comment by aivarannamaa** [comment] 2024-09-11 09:43
Please try https://github.com/thonny/thonny/releases/download/v4.1.6/thonny-4.1.6.pkg

**Comment by nissaba** [comment] 2024-09-23 17:49
works thanks
