### ISSUE TITLE
No longer access to packages

### ISSUE THREAD

**Issue by lulu-vivi** [thonny/thonny#3405] opened 2024-12-17 11:03 UTC
Since recently, it's become impossible to install or even search for new packages. I'm new to Thonny, is there a fee to pay after a while ? So far there was no problem to search and install new packages...

**Comment by aivarannamaa** [comment] 2024-12-17 15:18
Please try version 4.1.7

**Comment by mblasee** [comment] 2024-12-17 15:53
Not working for me either, using 4.1.7 on Windows 11

**Comment by aivarannamaa** [comment] 2024-12-17 19:46
@mblasee, please re-check your version. If you really have 4.1.7, then please list the steps for reproducing the problem - including where you clicked, what you typed and what happened.

**Comment by mblasee** [comment] 2024-12-17 22:13
https://github.com/user-attachments/assets/02bf8325-d583-451b-a48c-57f72e9a3664

I recorded what I was doing but here are the steps as well

I typed help() to the repl to show that its not frozen and Thonny installation/esp firmware is fine.
I opened Help/About Thonny to verify my version, its 4.1.7
I opened Tools/Manage Packages typed aioble and pressed enter. Then nothing happens no matter how long I am waiting.

**Comment by mblasee** [comment] 2024-12-17 22:22
I was poking around a bit and seems like if I use "Local Python 3  ° Thonny's Python" mode it's working.
I was under the impression that this package install should work in esp32 mode as well, am I mistaken?

**Comment by SolarBites** [comment] 2024-12-18 20:36
@mblasee is it still working? mine wasnt working when i had the 4.1.6 version, but i downloaded the 4.1.7 and everything is fine. I can download packages which i couldnt in 4.1.6

**Comment by aivarannamaa** [comment] 2024-12-19 13:17
@mblasee, I see that the search button in your case is disabled. This may mean that Thonny is not ready with listing your installed packages.

Does the button change when you wait for 10 seconds after opening the package dialog?

If not, then please check which files you have in your `sys.path` directories. Here's how I check this:

```
>>> import sys
>>> sys.path
['', '/', '/lib']
>>> import os
>>> os.listdir("/lib")
[]
>>> os.listdir("/")
['sd', 'settings.toml', 'code.py', 'lib', 'boot_out.txt']
```

**Comment by mblasee** [comment] 2024-12-19 22:28
I don't know what happened since I didn't change any config or installed anything but it works now. Both in Local Python 3 ° Thonny's Python or MicroPython (ESP32) mode. 

Thanks for everyone's attention, I am fine with closing this issue.

**Comment by aivarannamaa** [comment] 2024-12-20 05:31
Great!

**Closed by aivarannamaa** 2024-12-20 05:31 UTC
