### ISSUE TITLE
Could not determine download URL

### ISSUE THREAD

**Issue by percygr** [thonny/thonny#2342] opened 2022-07-06 08:31 UTC
I've just got a new Pico W and nothing works. Please help 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/21970527/177506558-32c4261e-787f-45ae-962a-6caafaa74307.png">

**Comment by aivarannamaa** [comment] 2022-07-06 09:50
I don't have a Pico W myself (yet). 

Could you please send me the content of INFO_UF2.TXT on your Pico bootloader drive -- the drive that appears in your Windows Explorer after you plug in Pico while holding BOOTSEL. When you took the screenshot it was called `J:` drive.

**Comment by percygr** [comment] 2022-07-06 10:44
btw, sorry about the frustrated nature of the original post, the reason for this is here -https://forums.raspberrypi.com/viewtopic.php?t=337056

**Comment by aivarannamaa** [comment] 2022-08-01 14:53
That's strange. I received my Pico W and I can't reproduce this issue.

Does it still happen for you?

**Comment by stanelie** [comment] 2022-09-07 18:20
I have the same issue.

Same raspberry PI pico, same error message...

**Comment by stanelie** [comment] 2022-09-07 18:59
Fixed it myself : 
I grabbed the UF2 file from https://www.raspberrypi.com/documentation/microcontrollers/micropython.html and dropped it in the Pico's filesystem, it rebooted and now shows a com port that Thonny can connect to.

**Comment by aivarannamaa** [comment] 2022-09-08 07:21
I'm closing this, because the flashing dialog is refactored in Thonny 4.0

**Closed by aivarannamaa** 2022-09-08 07:21 UTC
Labels: MicroPython
