### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by taqi59a** [thonny/thonny#3308] opened 2024-09-09 09:51 UTC
Thonny is crashing on Mac after new update in Mac OS

**Comment by aivarannamaa** [comment] 2024-09-11 16:21
Duplicate of #3283. Please try https://github.com/thonny/thonny/releases/download/v4.1.6/thonny-4.1.6.pkg

**Closed by aivarannamaa** 2024-09-11 16:21 UTC

**Comment by impenz** [comment] 2024-09-12 00:28
> Duplicate of #3283. Please try https://github.com/thonny/thonny/releases/download/v4.1.6/thonny-4.1.6.pkg

it works. Thanks.
