### ISSUE TITLE
Not able to save/edit content of Raspberry PI Pico with adafruit-circuitpython-raspberry_pi_pico-pt_BR-6.2.0-beta.3

### ISSUE THREAD

**Issue by gsrbr** [thonny/thonny#1690] opened 2021-03-09 00:47 UTC
Hello,
I'm get this error when I try to save files at my pico

```
ERROR thonny.backend: PROBLEM WITH THONNY'S BACK-END Error Could not open file /code.py for writing, output: [Errno 30] Sistema de arquivos somente leitura
```

Using: 
* CircuitPython  -> [adafruit-circuitpython-raspberry_pi_pico-pt_BR-6.2.0-beta.3](https://downloads.circuitpython.org/bin/raspberry_pi_pico/pt_BR/adafruit-circuitpython-raspberry_pi_pico-pt_BR-6.2.0-beta.3.uf2
)
* Thonny 3.3.5
* Windows 10 Pro 64-Bit

**Comment by aivarannamaa** [comment] 2021-03-09 07:32
Thank you for the report!

Your case seems to be duplicate of #1662 -- please subscribe to that issue in order to get updates about fixes.

**Closed by aivarannamaa** 2021-03-09 07:32 UTC
