### ISSUE TITLE
Window panes render with lines jamed up on each other

### ISSUE THREAD

**Issue by boardtc** [thonny/thonny#955] opened 2019-10-23 00:56 UTC
Is there anything that can be done about the lines in panes jamming up against each other? I can manage in variables but Program Tree is a disaster.
![program tree](https://user-images.githubusercontent.com/214808/67346920-466c7f00-f538-11e9-8dd4-a5a7027ed2c6.png)
![variables](https://user-images.githubusercontent.com/214808/67346921-466c7f00-f538-11e9-9b7d-65ee259dc9e6.png)

My screen is 3200x1800 with 250% scaling, moved to second monitor which has 1850x1050 with 100% scaling and it did not change.

**Comment by aivarannamaa** [comment] 2019-10-23 05:55
Please try different scaling rate in Tools => Options => General

**Comment by boardtc** [comment] 2019-10-23 21:53
Neither of the other 2 options made a difference, extra or automatic, I restarted Thonny each time.

**Comment by aivarannamaa** [comment] 2019-10-24 05:08
I'll see what I can do. Duplicate of #933

**Closed by aivarannamaa** 2019-10-24 05:08 UTC

**Comment by boardtc** [comment] 2019-10-26 10:31
Same issue on Variables pane. I added to [#933 ](https://github.com/thonny/thonny/issues/933#issuecomment-546543468)
