### ISSUE TITLE
Error when saving on the desktop

### ISSUE THREAD

**Issue by Jpn287** [thonny/thonny#875] opened 2019-09-01 15:52 UTC
### Hello. 
Here is the traceback of the bug :
```
Traceback (most recent call last):
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 601, in _cmd_save_file
    self.get_current_editor().save_file()
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 240, in save_file
    f.flush()
OSError: [Errno 9] Bad file descriptor
```

The software doesn't save even in admin mode. But it can save on a parent directory like : 
`C:\Users\user1`
What to do ?

**Comment by aivarannamaa** [comment] 2019-09-01 18:31
Duplicate of #833

**Closed by aivarannamaa** 2019-09-01 18:31 UTC
