### ISSUE TITLE
Debugger has some broken graphics

### ISSUE THREAD

**Issue by isaacl** [thonny/thonny#2458] opened 2022-09-14 11:42 UTC
The last step before the debugger invokes a function stays on the screen, over the top of the new function pop up.

![image](https://user-images.githubusercontent.com/1027886/190144149-81bf151e-ba74-4e41-82da-98482cb3b454.png)

It also shows even when thonny is not the top window :-o (system: OS X)

![image](https://user-images.githubusercontent.com/1027886/190144395-bb3e68b1-dbbe-4b20-9eed-6e6ee8139c5a.png)

Sample code:
```python
def f2(v):
    return v

def main():
    f2(2)

main()
```

**Comment by aivarannamaa** [comment] 2022-09-19 07:11
Thank you for this report!

I'll try to reproduce and fix this later.

**Comment by isaacl** [comment] 2022-09-19 13:54
My students with Windows did not see this issue, FWIW.   I think it is OS X specific.

**Comment by aivarannamaa** [comment] 2023-07-05 05:16
I can't reproduce this in Thonny 4.1.1. I assumed it is fixed by now. Please reopen if you still have this problem with latest Thonny.

**Closed by aivarannamaa** 2023-07-05 05:16 UTC
