### ISSUE TITLE
Find & Replace doen't work

### ISSUE THREAD

**Issue by speedy-10** [thonny/thonny#2208] opened 2022-03-22 14:26 UTC
Hi, if  I try to use 'crtl + F' there is no reaction of thonny, but the cursor moves one character to the right.

thonny 4.0.0b1

 A further observation:
- In the german menu Datei > "Move/rename" could be translated to "Verschieben/Umbenennen"
- in the menu  Extras > Optionen > Editor: there are missing some German translations, see picture.
->
![Bildschirmfoto von 2022-03-22 15-22-15](https://user-images.githubusercontent.com/20227451/159504468-d0c1ede6-e72a-4d45-b4ee-22d5c67eefd0.png)
 
Regards

**Comment by aivarannamaa** [comment] 2022-03-23 04:47
Thank you for the report! The problem is now fixed.

Regarding translations -- I don't write them myself. Please see https://github.com/thonny/thonny/blob/master/docs/translate.md#short-story-for-translators for the instructions.

**Closed by aivarannamaa** 2022-03-23 04:47 UTC

**Comment by speedy-10** [comment] 2022-03-30 14:57
ok, I registered myself here: https://poeditor.com/projects/po_edit?id_language=55&id=...
There are no strings left to translate (because beta?), so I'll wait for the next "full version" of thonny and support it then.
