### ISSUE TITLE
Is Code Folding Available in 'thonny'??

### ISSUE THREAD

**Issue by mjarboe5** [thonny/thonny#1257] opened 2020-07-07 19:47 UTC
Is there an option for Code Folding in thonny?
A way to _collapse_ sections of code?  Instead of displaying the entire 
**def get_text**(receiving_socket) 
    ...
    ...
_Is there an option to collapse (to show 1 line) and expand back to full view?_

_**def get_text**(receiving_socket):
    buffer = ""
    socket_open = True
    while socket_open:
        # read any data from the socket
        data = receiving_socket.recv(1024)

        # if no data is returned the socket must be closed
        if not data:
            socket_open = False
        
        # add the data to the buffer
        buffer = buffer + data.decode()
        # is there a terminator in the buffer
        terminator_pos = buffer.find("\n")
        # if the value is greater than -1, a \n must exist
        while terminator_pos > -1:
            # get the message from the buffer
            message = buffer[:terminator_pos]
            # remove the message from the buffer
            buffer = buffer[terminator_pos + 1:]
            # yield the message (see below)
            yield message
            # is there another terminator in the buffer
            terminator_pos = buffer.find("\n")_

**Comment by aivarannamaa** [comment] 2020-07-08 05:24
Duplicate of #1090

**Closed by aivarannamaa** 2020-07-08 05:24 UTC
