### ISSUE TITLE
select interpreter problem

### ISSUE THREAD

**Issue by Pooria4484** [thonny/thonny#1458] opened 2020-12-02 11:15 UTC
Traceback (most recent call last):
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1044, in dispatch_from_menu
    dispatch(None)
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 986, in dispatch
    handler()
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 469, in cmd_stop_restart
    self.restart_backend(True)
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 600, in restart_backend
    self._proxy = backend_class(clean)
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 82, in __init__
    self._fix_port()
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 118, in _fix_port
    elif not port_exists(self._port):
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 879, in port_exists
    for port in list_serial_ports():
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 873, in list_serial_ports
    return list(serial.tools.list_ports.comports())
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\serial\tools\list_ports_windows.py", line 412, in comports
    return list(iterate_comports())
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\serial\tools\list_ports_windows.py", line 334, in iterate_comports
    info.serial_number = get_parent_serial_number(devinfo.DevInst, info.vid, info.pid)
  File "C:\Users\Pooria\AppData\Local\Programs\Thonny\lib\site-packages\serial\tools\list_ports_windows.py", line 197, in get_parent_serial_number
    vid = int(m.group(1), 16)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by aivarannamaa** [comment] 2020-12-02 11:50
Thank you for the report!

It looks like duplicate of #1443 and the fix will be released soon.

**Closed** 2021-01-16 15:49 UTC
