### ISSUE TITLE
no print output from remote via ssh 

### ISSUE THREAD

**Issue by EriHau** [thonny/thonny#2249] opened 2022-04-16 16:33 UTC
I am a beginner. Please forgive me if this problem is not a bug but a user error.
I run my python code on a headless raspberry pi and the thonny IDE runns on my Ubuntu-Laptop. Interpreter is "Remote Python 3 (SSH)". With the version 3.3.13 all works fine and I get all print outputs from my code and also error messages. 
Due to the file size error I switched to 4.0.0b2. Unfortunately I get no print output to the Shell window. The only message I get is ">>> %Run -c $EDITOR_CONTENT". But my code is running on my remote pi as I got messages over mqtt. An also when I put a syntax failure into my code there is no error message from the interpreter when trying to run the code. 
The windows which shows the remote files is also empty.   

**3.3.13:**
![Screenshot from 2022-04-16 18-26-50](https://user-images.githubusercontent.com/43499790/163683364-0a9d5cba-51e4-4a4d-bed0-9ca244c50b16.png)

**4.0.0b2:**
![Screenshot from 2022-04-16 18-24-53](https://user-images.githubusercontent.com/43499790/163683396-e30f658e-11cb-473f-827b-efdff9d7c73f.png)

**Comment by aivarannamaa** [comment] 2022-04-18 06:43
Thank you for the report!

Which OS are you using for Thonny? 

I can't reproduce this problem with simple `print`-s. Can you give me the simplest program that exposes this problem on your computer?

**Comment by EriHau** [comment] 2022-04-18 11:10
Thonny runs on **Ubuntu 20.04.4 LTS**
On my remote raspberry I have Raspbian 11 bullseye in headless mode. 

My simplest test-code:
```
import sys
print ("hello world")
with open('filename.txt', 'w') as f:
    print('hello filesystem', file=f)
```

You can see: no output
![Screenshot from 2022-04-18 13-05-18](https://user-images.githubusercontent.com/43499790/163799937-2ebb5384-9153-48d2-8989-53bdd6659813.png)

The file I can see at the remote:
![Screenshot from 2022-04-18 13-05-48](https://user-images.githubusercontent.com/43499790/163799979-597057e2-d45c-4859-8cd4-16f6ac47b588.png)

But it's not only the print output, which is not shown. When I connect to the remote, there is also no line with the path- and version-information shown in the shell window. The shell is complete empty. No prompt, nothing. Just when I start the code, it looks like in the screenshot above.

**Comment by aivarannamaa** [comment] 2022-04-18 20:48
Thanks!

I found the bug. The fix will be in the next beta.

**Closed** 2022-04-18 20:47 UTC
Labels: ssh
