### ISSUE TITLE
Manage Packages Crashes If Entered Directly

### ISSUE THREAD

**Issue by hersephone** [thonny/thonny#3315] opened 2024-09-17 05:45 UTC
If I go to Manage Packages, the app lags out (spinning beachball of death) and I have to force quit it. If I go to Options first and *then* Manage Packages, it works.

**Comment by aivarannamaa** [comment] 2024-10-12 06:41
Sorry for the late reply!

Which Thonny version and which OS version are you using?

**Comment by hersephone** [comment] 2024-10-13 12:56
Thonny 4.6.1. Sonoma 14.6.1. Thank you for replying! It's not that awful a bug (like I said it works if i open a different menu directly before it), but it is weird.

**Comment by aivarannamaa** [comment] 2024-11-26 12:14
Unfortunately I can't reproduce this. I'll close this, as the package management will be thoroughly reworked in the next version.

**Closed by aivarannamaa** 2024-11-26 12:14 UTC
Labels: package management
