### ISSUE TITLE
Pastes twice when CapsLock on

### ISSUE THREAD

**Issue by bgiobbe** [thonny/thonny#2753] opened 2023-04-19 22:47 UTC
I'm on Thonny 4.0.2, MacOS 12.6.3 Monterey, MacBook Pro (15-inch, 2018).

When the caps lock is on, cmd-v pastes what I copied twice.
Example:
  * caps lock off
     * Select Y_MARGIN
     * cmd-c
     * cmd-v: pastes  Y_MARGIN
  * caps lock on
     * Select Y_MARGIN
     * cmd-c
     * cmd-v: pastes  Y_MARGINY_MARGIN

**Comment by aivarannamaa** [comment] 2023-04-22 11:41
Thanks for the report!

I could reproduce this with Tk 8.6.12 but the problem seems to be fixed in Tk 8.6.13.

Most likely I'll bundle Tk 8.6.13 with the next Thonny version (4.1.0)

**Comment by aivarannamaa** [comment] 2023-04-25 05:11
First beta of 4.1.0 is now available: https://github.com/thonny/thonny/releases/tag/v4.1.0b1

**Closed by aivarannamaa** 2023-04-25 05:11 UTC
Labels: macOS, tk

**Comment by bgiobbe** [comment] 2023-04-26 02:10
I installed v4.1.0b1 and tried copying and pasting with caps lock on. It
worked as expected. This bug is fixed! Thanks for tracking it down and
fixing it :)

Beth Giobbe
