### ISSUE TITLE
updated Thonny, getting management errors

### ISSUE THREAD

**Issue by dalemcbeath** [thonny/thonny#1783] opened 2021-04-27 16:54 UTC
Hi, updated **Thonny 3.3.6**  (Mac OS X 10.15.7)  and am getting a management error when running the following code from the GitHub examples at https://github.com/raspberrypi/pico-micropython-examples/blob/master/multicore/multicore.py on an **rp2040 PICO**.

not sure if the update and the errors are related, maybe just coincidence, as I didn't try this particular code before the update.

errors aren't always the same, but happen each time the example is run.   Unplugging the usb power for the rp2020 and restarting Thonny didn't help. (I think the 2nd core continues to run even when Thonny stop button pressed?)

thanks

```python
import time, _thread, machine

def task(n, delay):
    led = machine.Pin(25, machine.Pin.OUT)
    for i in range(n):
        led.high()
        time.sleep(delay)
        led.low()
        time.sleep(delay)
    print('done')

_thread.start_new_thread(task, (10, 0.5))`
```

```
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/workbench.py", line 1708, in event_generate
    handler(event)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/shell.py", line 433, in _handle_program_output
    self._update_visible_io(None)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/shell.py", line 512, in _update_visible_io
    self._apply_io_event(data, stream_name)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/shell.py", line 555, in _apply_io_event
    self.active_extra_tags.pop()
IndexError: pop from empty list
```

and on other runs of same code:

```
─────────────────────────────────────
MicroPython v1.15 on 2021-04-18; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
THONNY FAILED TO EXECUTE COMMAND Run


SCRIPT:

class __thonny_helper:
    try:
        import uos as os
    except ImportError:
        import os
    import sys

    # for object inspector
    inspector_values = dict()
    last_repl_values = []
    @classmethod
    def print_repl_value(cls, obj):
        if obj is not None:
            cls.last_repl_values.append(obj)
            cls.last_repl_values = cls.last_repl_values[-5:]
            print('[object_link_for_thonny=%d]' % id(obj), repr(obj), '', sep='')

    @staticmethod
    def print_mgmt_value(obj):
        print('<thonny>', repr(obj), '</thonny>', sep='', end='')

    @staticmethod
    def repr(obj):
        try:
            s = repr(obj)
            if len(s) > 50:
                s = s[:50] + "..."
            return s
        except Exception as e:
            return "<could not serialize: " + str(e) + ">"

    @classmethod
    def listdir(cls, x):
        if hasattr(cls.os, "listdir"):
            return cls.os.listdir(x)
        else:
            return [rec[0] for rec in cls.os.ilistdir(x) if rec[0] not in ('.', '..')]


    @classmethod
    def getcwd(cls):
        if hasattr(cls, "getcwd"):
            return cls.os.getcwd()
        else:
            # micro:bit
            return ""

    @classmethod
    def chdir(cls, x):
        return cls.os.chdir(x)

    @classmethod
    def rmdir(cls, x):
        return cls.os.rmdir(x)


STDOUT:


STDERR:
Traceback (most recent call last):
  File "<stdin>", line 6
SyntaxError: invalid syntax


ManagementError
>>> done
THONNY FAILED TO EXECUTE COMMAND get_globals


SCRIPT:
__thonny_helper.print_mgmt_value({name : (__thonny_helper.repr(value), id(value)) for (name, value) in globals().items() if not name.startswith('__')})

STDOUT:


STDERR:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '__thonny_helper' isn't defined
```

 --- popup window ---
"problem handling program output"

```
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/workbench.py", line 1708, in event_generate
    handler(event)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/shell.py", line 433, in _handle_program_output
    self._update_visible_io(None)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/shell.py", line 512, in _update_visible_io
    self._apply_io_event(data, stream_name)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/shell.py", line 555, in _apply_io_event
    self.active_extra_tags.pop()
IndexError: pop from empty list
```

**Comment by aivarannamaa** [comment] 2021-04-27 18:37
Thank you for the report! This seems to be duplicate of #1586. You may want to vote for https://github.com/micropython/micropython/issues/6899 to speed up fixing the source of the problem.

**Closed by aivarannamaa** 2021-04-27 18:37 UTC
Labels: MicroPython
