### ISSUE TITLE
Overwrite dialog opens in background

### ISSUE THREAD

**Issue by wnelis** [thonny/thonny#1250] opened 2020-06-26 07:58 UTC
Using Thonny 3.2.7 on Linux Mint 19.3. When saving a modified  file back to an ESP8266, the "Overwrite" dialog opens but is invisible as it is hidden by the "Save to MicroPython device" dialog. This seems similar to issue #1133.

**Comment by aivarannamaa** [comment] 2020-06-26 13:47
Thank you for reporting it!

Does it happen occasionally or always?

**Comment by wnelis** [comment] 2020-06-26 19:20
It happened every time I saved a modified file on the ESP8266, thus far. Thus it basically happens always.

**Comment by aivarannamaa** [comment] 2020-09-28 10:03
Duplicate of #1158

**Closed by aivarannamaa** 2020-09-28 10:03 UTC
Labels: MicroPython, dialogs, tk
