### ISSUE TITLE
micropython-umqtt.simple does not install

### ISSUE THREAD

**Issue by artspace133** [thonny/thonny#2524] opened 2022-10-29 13:36 UTC
The micropython-umqtt.simple packace does not install correctly.
The version is 1.3.4

![Screenshot 2022-10-26 112655](https://user-images.githubusercontent.com/58709738/198834521-c95b264e-21b1-4218-875a-cff6d673fcf5.png)

**Comment by aivarannamaa** [comment] 2022-10-29 20:30
Thank you for the report!

Is this also your message: https://groups.google.com/g/thonny/c/0jtdT07nPYQ ?

**Comment by artspace133** [comment] 2022-10-29 22:42
Thank You,
The message from the google groups is from another user.

**Comment by mbradley612** [comment] 2022-11-26 12:09
Follow the instruction here to install these libraries on a RPi Pico using Thonny: https://www.hivemq.com/blog/iot-reading-sensor-data-raspberry-pi-pico-w-micropython-mqtt-node-red/. You'll need to install both umqtt.simple and umqtt.robust.

'''
import upip
upip.install(“micropython-umqtt.robust”)
upip.install(“micropython-umqtt.simple”)
'''

**Comment by artspace133** [comment] 2022-11-28 20:06
I have had no luck trying to install the work around mentioned in this blog
post. I'm stuck until this is fixed...
Thanks to all, please let me know if anyone has got this to work...

**Comment by jesper-johansen** [comment] 2022-11-28 20:56
It looks as upip is replaced with mip, so for me the following is working
>>>import mip
>>>mip.install('umqtt.simple')
>>>mip.install('umqtt.robust')
regards Jesper

**Comment by artspace133** [comment] 2022-11-28 22:45
When I tried to install "mip", a message indicated that the package is
intended for circuit python use, and it failed...
I'm using a Pico W... Sorry to all that I didn't mention that...

Justin Parker

**Comment by GAZDOWN** [comment] 2022-11-29 07:07
> It looks as upip is replaced with mip, so for me the following is working
> 
> > > > import mip
> > > > mip.install('umqtt.simple')
> > > > mip.install('umqtt.robust')
> > > > regards Jesper

Hi I can confirm this indeed works.

**Comment by marcelomaiajuvencio** [comment] 2022-12-05 22:53
Hello!!!
How to solve:
download the micropython-umqtt.simple-1.3.4.tar package at [https://pypi.org/project/micropython-umqtt.simple/#files](https://pypi.org/project/micropython-umqtt.simple/#files)
![image](https://user-images.githubusercontent.com/18221120/205759249-fb48d96e-a7ee-4201-a3ed-9d6de9703488.png)

Extract the micropython-umqtt.simple-1.3.4.tar package
![image](https://user-images.githubusercontent.com/18221120/205759434-e3530949-071c-4c2b-9288-989ff3bdde1b.png)

Using Thonny, with Pico connected, navigate to the umqtt folder
![image](https://user-images.githubusercontent.com/18221120/205759709-68a32085-9dea-4090-aa9e-aacdbc81deda.png)

Right click on the umqtt folder > Upload to/
![image](https://user-images.githubusercontent.com/18221120/205759981-deff7c6e-c1bf-4ab3-92b0-8082d0acb05c.png)

The folder will be copied on Pico
![image](https://user-images.githubusercontent.com/18221120/205760218-c270fef6-7617-4188-84ea-a23a061713f2.png)

Ready, just import and use
`from umqtt.simple import MQTTClient`

**Comment by artspace133** [comment] 2022-12-05 23:42
Thank you very much, I finally got this working on my Pick W...

Thanks again,
Justin Parker

**Comment by aivarannamaa** [comment] 2022-12-28 16:56
I fixed the root cause in pipkin (https://github.com/aivarannamaa/pipkin/issues/4) and the fix will be published as part of Thonny 4.0.4

**Comment by aivarannamaa** [comment] 2022-12-31 09:26
Fixed by 79625901

**Closed by aivarannamaa** 2022-12-31 09:26 UTC
Labels: MicroPython, package management, pipkin

**Comment by marcelomaiajuvencio** [comment] 2023-01-11 23:03
Hello, I tried with mip but it didn't work either. So I adopted the manual installation procedure.



    Em segunda-feira, 9 de janeiro de 2023 23:16:38 BRT, tpilutti ***@***.***> escreveu:  
 
 


Hi-
tried the mip approach

import mip
mip.install('umqtt.simple')
mip.install('umqtt.robust')




import mip
mip.install('umqtt.simple')
Installing umqtt.simple (latest) from https://micropython.org/pi/v2 to /lib
Traceback (most recent call last):
File "", line 1, in 
File "mip/init.py", line 1, in install
File "mip/init.py", line 1, in _install_package
File "mip/init.py", line 1, in _install_json
File "urequests.py", line 180, in get
File "urequests.py", line 76, in request
OSError: -6




Is there something I should check on my side?
Thx.

**Comment by tpilutti** [comment] 2023-01-27 15:01
Hi - anyone know if Issue 2524 was resolved in Thonny release 4.0.2? Didn't see this issue number in the 4.0.2 release notes.  Thanks.

**Comment by aivarannamaa** [comment] 2023-01-27 15:20
Yes, this should be fixed in 4.0.2.

**Comment by tpilutti** [comment] 2023-01-29 01:50
Thanks! ManagePackages tool in 4.0.2 looks like it installed successfully. 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/6383792/215299890-1fd64053-7b59-4077-bb26-9d468f021a50.png">

**Comment by ElToro1966** [comment] 2023-03-01 11:33
On Thonny 3.2.7:
>>> import mip
>>> mip.install("umqtt.simple")
Installing umqtt.simple (latest) from https://micropython.org/pi/v2 to /lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mip/__init__.py", line 1, in install
  File "mip/__init__.py", line 1, in _install_package
  File "mip/__init__.py", line 1, in _install_json
  File "urequests.py", line 180, in get
  File "urequests.py", line 76, in request
OSError: -6

However:
>>> wlan = network.WLAN(network.STA_IF)
>>> wlan.active(True)
>>> wlan.connect('wifi_ssid', 'wifi_pw')
>>> import mip
>>> mip.install("umqtt.simple")
Installing umqtt.simple (latest) from https://micropython.org/pi/v2 to /lib
Copying: /lib/umqtt/simple.mpy
Done
>>>

**Comment by ArPiSo** [comment] 2023-07-12 23:15
![image](https://github.com/thonny/thonny/assets/113214220/ce676c91-7e11-4c17-91cc-5cf8d7f4fcfc)


C:\Users\ПК\AppData\Local\Programs\Thonny\python.exe -m pip --disable-pip-version-check --no-color install --no-warn-script-location --user --user --upgrade micropython-umqtt.simple
Requirement already satisfied: micropython-umqtt.simple in c:\users\РїРє\appdata\roaming\thonny\plugins\python310\site-packages (1.1)
Collecting micropython-umqtt.simple
  Using cached micropython-umqtt.simple-1.3.4.tar.gz (4.0 kB)
ERROR: micropython-umqtt.simple from https://files.pythonhosted.org/packages/bd/cf/697e3418b2f44222b3e848078b1e33ee76aedca9b6c2430ca1b1aec1ce1d/micropython-umqtt.simple-1.3.4.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Error: process returned with code 1

**Comment by aivarannamaa** [comment] 2023-07-23 05:32
@ArPiSo, it looks like you were trying to install a MicroPython package as Thonny plug-in. Please read the text on the top of your screenshot.
