### ISSUE TITLE
Load the default theme if a configured one is missing

### ISSUE THREAD

**Issue by tabreturn** [thonny/thonny#2149] opened 2022-01-31 01:37 UTC
I'm suggesting that Thonny include some workaround to load the default theme if a configured one is missing (i.e. if/when the user uninstalls/deletes a theme). Right now, if the configured theme is missing, Thonny simply won't start.

**System**
Thonny 3.3.7 (I need Python 3.8 on Linux)
Affects Linux, Windows (and surely macOS, too).

**To replicate the issue**
Install a theme from the plugin manager, say [thonny-onedark](https://github.com/ranelpadon/thonny-onedark/blob/main/thonnycontrib/onedark/__init__.py). Restart Thonny, then apply that theme. Now uninstall thonny-onedark (or delete it somehow). Next time you open Thonny it will crash because it cannot find the theme.

**Comment by aivarannamaa** [comment] 2022-01-31 05:31
Thank you for the report! Actually, someone was faster and the problem is fixed under #2117. The fix will be in the first beta of 4.0

**Closed by aivarannamaa** 2022-01-31 05:31 UTC
